sonar.projectKey=verificacion-jenkins
sonar.projectName=verificacion-jenkins
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.surefire.reportPaths=target/surefire-reports